EXCEL_PATH = "data/capbudg.xls"

KNOWN_TABLES = [
    "INITIAL INVESTMENT", "CASHFLOW DETAILS", "DISCOUNT RATE",
    "WORKING CAPITAL", "GROWTH RATES", "SALVAGE VALUE",
    "OPERATING CASHFLOWS", "Investment Measures", "BOOK VALUE & DEPRECIATION"
]
